"""empty message

Revision ID: d8634752769e
Revises: bcd0477ce177
Create Date: 2022-03-29 00:53:31.599829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8634752769e'
down_revision = 'bcd0477ce177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task'),
    sa.UniqueConstraint('task')
    )
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index('task', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'task')
    op.drop_column('user', 'done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('task', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('task', 'user', ['task'], unique=False)
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    op.drop_table('todo')
    # ### end Alembic commands ###
